---
name: local-lib-deps
version: 0.02
author: []
abstract: This module uses local::lib to allow applications to maintain a private path of dependancy modules.
license: perl
resources:
  license: http://dev.perl.org/licenses/
provides:
  local::lib::deps:
    file: lib/local/lib/deps.pm
    version: 0.02
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
